Repository SMUMC-7th/Team-A-BE, pull requests merged in 2024-11, with the labels that each got.

#9 ♻️ [REFACTOR}: User 부분 리팩토링
  src/main/java/com/example/echo/domain/security/config/SecurityConfig.java
  src/main/java/com/example/echo/domain/security/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/echo/domain/user/controller/UserController.java
  src/main/java/com/example/echo/domain/user/converter/UserConverter.java
  src/main/java/com/example/echo/domain/user/dto/request/UserReqDto.java
  src/main/java/com/example/echo/domain/user/dto/response/UserResDto.java
  src/main/java/com/example/echo/domain/user/entity/AuthType.java
  src/main/java/com/example/echo/domain/user/entity/User.java
  src/main/java/com/example/echo/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/echo/domain/user/service/command/UserCommandService.java
Labels: feat, fix, refactor

#16 ✨feat: 이메일 인증 구현
  build.gradle
  src/main/java/com/example/echo/domain/email/controller/EmailAuthController.java
  src/main/java/com/example/echo/domain/email/exception/EmailErrorCode.java
  src/main/java/com/example/echo/domain/email/service/DefaultEmailSender.java
  src/main/java/com/example/echo/domain/email/service/EmailAuthService.java
  src/main/java/com/example/echo/domain/user/controller/UserController.java
  src/main/java/com/example/echo/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/echo/domain/user/service/command/UserCommandService.java
  src/main/java/com/example/echo/global/config/EmailConfig.java
Labels: feat, refactor

#17 ♻️refactor: deadline 타입 변경
  src/main/java/com/example/echo/domain/capsule/converter/CapsuleConverter.java
  src/main/java/com/example/echo/domain/capsule/dto/response/CapsuleResDTO.java
Labels: refactor

#19 ♻️refactor: 일반 로그인 응답 통일
  src/main/java/com/example/echo/domain/security/global/filter/CustomLoginFilter.java
Labels: refactor

#21 ♻️refactor: isOpened 수정
  src/main/java/com/example/echo/domain/capsule/converter/CapsuleConverter.java
Labels: refactor

#20 ✨ feat: 푸시 알림 기능 구현 (#13)
  build.gradle
  src/main/java/com/example/echo/domain/notification/controller/FcmController.java
  src/main/java/com/example/echo/domain/notification/converter/NotificationConverter.java
  src/main/java/com/example/echo/domain/notification/dto/request/NotificationReqDto.java
  src/main/java/com/example/echo/domain/notification/dto/response/NotificationResDto.java
  src/main/java/com/example/echo/domain/notification/entity/Noti.java
  src/main/java/com/example/echo/domain/notification/exception/NotificationErrorCode.java
  src/main/java/com/example/echo/domain/notification/exception/NotificationException.java
  src/main/java/com/example/echo/domain/notification/repository/NotificationRepository.java
  src/main/java/com/example/echo/domain/notification/service/command/FcmService.java
  src/main/java/com/example/echo/domain/notification/service/command/FcmTokenService.java
  src/main/java/com/example/echo/domain/notification/service/query/FcmQueryService.java
  src/main/java/com/example/echo/global/config/FirebaseConfig.java
Labels: feat

#25 ♻️ refactor: 로그인 로그아웃 응답 통일, 회원 탈퇴 수정
  build.gradle
  src/main/java/com/example/echo/EchoApplication.java
  src/main/java/com/example/echo/domain/security/global/filter/CustomLoginFilter.java
  src/main/java/com/example/echo/domain/security/global/filter/CustomLogoutHandler.java
  src/main/java/com/example/echo/domain/user/controller/UserController.java
  src/main/java/com/example/echo/domain/user/repository/UserReposiotry.java
  src/main/java/com/example/echo/domain/user/service/command/UserCommandService.java
Labels: refactor

#28 ♻️refactor: 비밀번호 찾기 로직 수정
  src/main/java/com/example/echo/domain/email/controller/EmailAuthController.java
  src/main/java/com/example/echo/domain/email/service/EmailAuthService.java
  src/main/java/com/example/echo/domain/security/config/SecurityConfig.java
  src/main/java/com/example/echo/domain/user/controller/UserController.java
  src/main/java/com/example/echo/domain/user/dto/request/UserReqDto.java
  src/main/java/com/example/echo/domain/user/service/command/UserCommandService.java
Labels: refactor

#29 ✨ feat: AWS S3 이미지 기능 구현
  build.gradle
  src/main/java/com/example/echo/domain/capsule/config/AwsS3Config.java
  src/main/java/com/example/echo/domain/capsule/config/ChatGPTConfig.java
  src/main/java/com/example/echo/domain/capsule/controller/CapsuleController.java
  src/main/java/com/example/echo/domain/capsule/converter/CapsuleConverter.java
  src/main/java/com/example/echo/domain/capsule/dto/request/CapsuleReqDTO.java
  src/main/java/com/example/echo/domain/capsule/dto/response/CapsuleResDTO.java
  src/main/java/com/example/echo/domain/capsule/entity/Capsule.java
  src/main/java/com/example/echo/domain/capsule/entity/Image.java
  src/main/java/com/example/echo/domain/capsule/entity/enums/TagName.java
  src/main/java/com/example/echo/domain/capsule/exception/code/AwsS3ErrorCode.java
  src/main/java/com/example/echo/domain/capsule/exception/code/CapsuleErrorCode.java
  src/main/java/com/example/echo/domain/capsule/exception/code/ChatGPTErrorCode.java
  src/main/java/com/example/echo/domain/capsule/exception/code/ImageErrorCode.java
  src/main/java/com/example/echo/domain/capsule/exception/handler/AwsS3Exception.java
  src/main/java/com/example/echo/domain/capsule/exception/handler/CapsuleException.java
  src/main/java/com/example/echo/domain/capsule/exception/handler/ChatGPTException.java
  src/main/java/com/example/echo/domain/capsule/exception/handler/ImageException.java
  src/main/java/com/example/echo/domain/capsule/repository/ImageRepository.java
  src/main/java/com/example/echo/domain/capsule/service/AwsS3Service.java
  src/main/java/com/example/echo/domain/capsule/service/ChatGPTService.java
  src/main/java/com/example/echo/domain/capsule/service/command/CapsuleCommandService.java
  src/main/java/com/example/echo/domain/capsule/service/query/CapsuleQueryService.java
  src/main/java/com/example/echo/domain/notification/service/command/FcmService.java
Labels: feat

#31 ✨feat: 푸시알림 스케줄러 메서드 구현
  src/main/java/com/example/echo/domain/capsule/entity/Capsule.java
  src/main/java/com/example/echo/domain/capsule/repository/CapsuleRepository.java
  src/main/java/com/example/echo/domain/notification/dto/request/NotificationReqDto.java
  src/main/java/com/example/echo/domain/notification/service/command/FcmService.java
Labels: feat, refactor

#33 ♻️refactor: 이메일 인증 로직 수정
  src/main/java/com/example/echo/domain/email/controller/EmailAuthController.java
  src/main/java/com/example/echo/domain/email/service/EmailAuthService.java
  src/main/java/com/example/echo/domain/user/dto/request/UserReqDto.java
  src/main/java/com/example/echo/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/echo/domain/user/repository/UserReposiotry.java
  src/main/java/com/example/echo/domain/user/service/command/UserCommandService.java
Labels: refactor

#36 🐛 fix: capsule isOpened 수정
  src/main/java/com/example/echo/domain/capsule/converter/CapsuleConverter.java
  src/main/java/com/example/echo/domain/capsule/entity/Capsule.java
  src/main/java/com/example/echo/domain/capsule/service/query/CapsuleQueryService.java
Labels: bug

#39 🐛 fix: 빈 이미지 리스트 처리
  src/main/java/com/example/echo/domain/capsule/controller/CapsuleController.java
  src/main/java/com/example/echo/domain/capsule/service/AwsS3Service.java
  src/main/java/com/example/echo/domain/capsule/service/command/CapsuleCommandService.java
Labels: fix

#37 ♻️refactor: 로그인시 삭제 복구 로직 추가
  src/main/java/com/example/echo/domain/email/controller/EmailAuthController.java
  src/main/java/com/example/echo/domain/email/service/EmailAuthService.java
  src/main/java/com/example/echo/domain/security/config/SecurityConfig.java
  src/main/java/com/example/echo/domain/security/global/filter/CustomLoginFilter.java
  src/main/java/com/example/echo/domain/user/controller/UserController.java
  src/main/java/com/example/echo/domain/user/entity/User.java
  src/main/java/com/example/echo/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/echo/domain/user/repository/UserReposiotry.java
  src/main/java/com/example/echo/domain/user/service/command/UserCommandService.java
Labels: refactor

#42 ♻️refactor: 이메일 중복 에러 처리
  src/main/java/com/example/echo/domain/email/service/EmailAuthService.java
Labels: refactor

#45 ♻️refactor: 500에러 반환 값 수정
  src/main/java/com/example/echo/global/apiPayload/exception/handler/GlobalExceptionHandler.java
Labels: refactor

#47 ♻️ refactor: 이미지 삭제 로직 파라미터 수정
  src/main/java/com/example/echo/domain/capsule/controller/CapsuleController.java
  src/main/java/com/example/echo/domain/capsule/service/AwsS3Service.java
Labels: refactor

#49 ♻️ refactor: 이미지 업로드 시 multipartFile 단일선택으로 변경
  src/main/java/com/example/echo/domain/capsule/controller/CapsuleController.java
  src/main/java/com/example/echo/domain/capsule/service/AwsS3Service.java
Labels: refactor

#51 ♻️ refactor: 중간점검 피드백 반영
  src/main/java/com/example/echo/domain/capsule/controller/CapsuleController.java
  src/main/java/com/example/echo/domain/capsule/repository/CapsuleRepository.java
  src/main/java/com/example/echo/domain/capsule/service/command/CapsuleCommandService.java
  src/main/java/com/example/echo/domain/capsule/service/query/CapsuleQueryService.java
Labels: refactor

#53 ♻️refactor: 로그아웃 시 FCM 토큰 redis에서 삭제
  src/main/java/com/example/echo/domain/security/global/filter/CustomLogoutHandler.java
Labels: refactor
