Repository SMUMC-7th/Team-A-BE, pull requests merged in 2024-12, with the labels that each got.

#57 🐛fix: 로그아웃 시 FCM 토큰 redis에서 삭제하는 에러 수정
  src/main/java/com/example/echo/global/config/RedisConfig.java
Labels: bug, fix

#59 ♻️refactor: 이메일 인증코드 에러 처리
  src/main/java/com/example/echo/domain/email/controller/EmailAuthController.java
  src/main/java/com/example/echo/domain/email/service/EmailAuthService.java
  src/main/java/com/example/echo/domain/user/exception/UserErrorCode.java
  src/main/java/com/example/echo/domain/user/service/command/UserCommandService.java
Labels: refactor

#61 ♻️ refactor: 커서기반 페이지네이션 method 수정
  src/main/java/com/example/echo/domain/capsule/repository/CapsuleRepository.java
  src/main/java/com/example/echo/domain/capsule/service/query/CapsuleQueryService.java
Labels: refactor

#62 ✨ feat: User, Email API Swagger Response 형식 추가
  src/main/java/com/example/echo/domain/email/controller/EmailAuthController.java
  src/main/java/com/example/echo/domain/email/dto/EmailRequestDto.java
  src/main/java/com/example/echo/domain/security/controller/AuthController.java
  src/main/java/com/example/echo/domain/security/dto/LoginRequestDto.java
  src/main/java/com/example/echo/domain/user/controller/UserController.java
  src/main/java/com/example/echo/domain/user/dto/request/UserReqDto.java
Labels: feat

#63 ✨feat: 푸시알림 API Swagger Response 형식 추가
  src/main/java/com/example/echo/domain/notification/controller/FcmController.java
Labels: feat

#69 ♻️ refactor: AI 질문 기능 동기로 변경
  src/main/java/com/example/echo/domain/capsule/controller/CapsuleController.java
  src/main/java/com/example/echo/domain/capsule/converter/CapsuleConverter.java
  src/main/java/com/example/echo/domain/capsule/service/ChatGPTService.java
Labels: refactor

#73 🐛fix: FCM 토큰 redis 저장방식 변경
  src/main/java/com/example/echo/domain/notification/service/command/FcmTokenService.java
  src/main/java/com/example/echo/global/config/RedisConfig.java
  src/main/java/com/example/echo/global/util/RedisUtil.java
Labels: bug, fix

#74 ✨ feat: 캡슐 수정 기능 구현
  src/main/java/com/example/echo/domain/capsule/controller/CapsuleController.java
  src/main/java/com/example/echo/domain/capsule/dto/request/CapsuleReqDTO.java
  src/main/java/com/example/echo/domain/capsule/entity/Capsule.java
  src/main/java/com/example/echo/domain/capsule/service/command/CapsuleCommandService.java
Labels: feat

#78 🐛 fix: AI 파싱응답 empty 에러처리
  src/main/java/com/example/echo/domain/capsule/service/ChatGPTService.java
Labels: fix
